---
title: "Survival Analysis of Apprenticeship Completions"
output: flexdashboard::flex_dashboard
runtime: shiny
resource_files:
- out/actual_plus_forecast.rds
- out/at_risk_plus_forecast.rds
- out/diagnosis.csv
- out/observed_vs_backcast.rds
- out/survival.rds
---

```{r}
library(tidyverse)
library(here)
library(conflicted)
library(plotly)
conflicts_prefer(dplyr::filter)
font_size=18
my_survplot <- function(mod, dat, grp) {
  plt <- survminer::ggsurvplot(mod,
    dat,
    censor = FALSE,
    conf.int = FALSE,
    ggtheme = theme_grey(),
    font.title=font_size,
    font.x=font_size,
    font.y=font_size,
    font.tickslab=font_size,
    font.legend=font_size
  ) +
    labs(
      title = grp,
      x = "Months",
      y = ""
    )
}
my_dt <- function(tbbl) {
  DT::datatable(tbbl,
                filter = 'top',
                extensions = "Buttons",
                rownames = FALSE,
                options = list(
                  columnDefs = list(list(className = "dt-center", targets = "_all")),
                  paging = TRUE,
                  scrollX = TRUE,
                  scrollY = TRUE,
                  searching = TRUE,
                  ordering = TRUE,
                  dom = "Btip",
                  buttons = list(
                    list(extend = "csv", filename = "some_file_name"),
                    list(extend = "excel", filename = "some_file_name")
                  ),
                  pageLength = 20
                )
  )
}

survival <- read_rds(here("out","survival.rds"))
observed_vs_backcast <- read_rds(here("out","observed_vs_backcast.rds"))
at_risk_plus_forecast <- read_rds(here("out","at_risk_plus_forecast.rds"))
actual_plus_forecast <- read_rds(here("out","actual_plus_forecast.rds"))
```


Inputs {.sidebar data-width=400}
-------------------------------------

### Introduction:

* Registration for apprenticeship is a leading indicator of completion of apprenticeship.
* In this app we use survival analysis to uncover the dynamics governing the transition between registering for an apprenticeship and completion of apprenticeship: i.e. not everyone who registers completes, and the elapsed time between registration and completion varies across trade and time. 
* Specifically, we forecast the arrival rate of new registrants using exponential smoothing, and then apply the joint probabilities of completion to the arrival rate to get the expected number of completions.

### What makes a good forecast:

1) A reasonable forecast of arrivals (the rate of arrival of new registrants is predictable)
2) Survival curves that are stable over time: here we split the 24 years of completion data into 3 eras of 8 years each, in order to ascertain whether the transition dynamics are stable.
3) Backcasts (applying the transition probabilities to historic new registrant arrival data) are close the observed values of completions.

```{r}
selectInput(
  "trade",
  "Choose a trade:",
  sort(survival$trade_desc),
  sort(survival$trade_desc)[1] 
)
```

Column
-------------------------------------
    
### Arrival rate of new apprentice registrations
    
```{r, fig.retina=2}
renderPlot({
  req(input$trade)
  at_risk_plus_forecast$plot[at_risk_plus_forecast$trade_desc==input$trade]
})
```
    
### Survival Curves

```{r, fig.retina=2}
renderPlot({
  req(input$trade)
  plt <- survival|>
    filter(trade_desc==input$trade)|>
    mutate(km_split_plot = pmap(list(km_split_model, data, trade_desc), my_survplot))
  plt$km_split_plot
})
```

Column
-------------------------------------

### Observed vs. Backcasts

```{r, fig.retina=2}
renderPlot({
  req(input$trade)
  observed_vs_backcast$plot[observed_vs_backcast$trade_desc==input$trade]
})
```

### Forecasts of Apprentice Completions
    
```{r, fig.retina=2}
renderPlot({
  req(input$trade)
  actual_plus_forecast$plot[actual_plus_forecast$trade_desc==input$trade]
})
```

